---
apiVersion: v1
kind: Secret
metadata:
  name: chatgpt
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  OPENAI_API_KEY: {{ .Values.chatgpt.token | b64enc | quote }}