---
apiVersion: v1
kind: Service
metadata:
  name: ai-deployment-namer
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app: ai-deployment-namer
